# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: telegram_bot_service.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class NotifyUserRequest(betterproto.Message):
    message: str = betterproto.string_field(1)
    user_id: int = betterproto.int64_field(2)


@dataclass
class NotifyUserResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


class TelegramBotServiceStub(betterproto.ServiceStub):
    async def notify_user(
        self, *, message: str = "", user_id: int = 0
    ) -> NotifyUserResponse:
        request = NotifyUserRequest()
        request.message = message
        request.user_id = user_id

        return await self._unary_unary(
            "/user_interactions.TelegramBotService/NotifyUser",
            request,
            NotifyUserResponse,
        )
