"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TaskType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TaskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    START_TRACKING: _TaskType.ValueType  # 0
    REVISIT_CHANNEL: _TaskType.ValueType  # 1

class TaskType(_TaskType, metaclass=_TaskTypeEnumTypeWrapper): ...

START_TRACKING: TaskType.ValueType  # 0
REVISIT_CHANNEL: TaskType.ValueType  # 1
global___TaskType = TaskType

class _TaskStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TaskStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PENDING: _TaskStatus.ValueType  # 0
    RUNNING: _TaskStatus.ValueType  # 1
    COMPLETED: _TaskStatus.ValueType  # 2
    FAILED: _TaskStatus.ValueType  # 3

class TaskStatus(_TaskStatus, metaclass=_TaskStatusEnumTypeWrapper): ...

PENDING: TaskStatus.ValueType  # 0
RUNNING: TaskStatus.ValueType  # 1
COMPLETED: TaskStatus.ValueType  # 2
FAILED: TaskStatus.ValueType  # 3
global___TaskStatus = TaskStatus

@typing.final
class Task(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    CHANNEL_ID_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    TASK_STATUS_FIELD_NUMBER: builtins.int
    task_id: builtins.int
    channel_id: builtins.int
    task_type: global___TaskType.ValueType
    task_status: global___TaskStatus.ValueType
    def __init__(
        self,
        *,
        task_id: builtins.int = ...,
        channel_id: builtins.int = ...,
        task_type: global___TaskType.ValueType = ...,
        task_status: global___TaskStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_id", b"channel_id", "task_id", b"task_id", "task_status", b"task_status", "task_type", b"task_type"]) -> None: ...

global___Task = Task

@typing.final
class CreateTaskRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    channel_id: builtins.int
    task_type: global___TaskType.ValueType
    def __init__(
        self,
        *,
        channel_id: builtins.int = ...,
        task_type: global___TaskType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_id", b"channel_id", "task_type", b"task_type"]) -> None: ...

global___CreateTaskRequest = CreateTaskRequest

@typing.final
class CreateTaskWithUserNotificationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    TASK_TYPE_FIELD_NUMBER: builtins.int
    USER_ID_TO_NOTIFY_FIELD_NUMBER: builtins.int
    channel_id: builtins.int
    task_type: global___TaskType.ValueType
    user_id_to_notify: builtins.int
    def __init__(
        self,
        *,
        channel_id: builtins.int = ...,
        task_type: global___TaskType.ValueType = ...,
        user_id_to_notify: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_id", b"channel_id", "task_type", b"task_type", "user_id_to_notify", b"user_id_to_notify"]) -> None: ...

global___CreateTaskWithUserNotificationRequest = CreateTaskWithUserNotificationRequest

@typing.final
class CreateTaskResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    task_id: builtins.int
    error_message: builtins.str
    def __init__(
        self,
        *,
        task_id: builtins.int = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "task_id", b"task_id"]) -> None: ...

global___CreateTaskResponse = CreateTaskResponse

@typing.final
class GetTaskRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    task_id: builtins.int
    def __init__(
        self,
        *,
        task_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["task_id", b"task_id"]) -> None: ...

global___GetTaskRequest = GetTaskRequest

@typing.final
class GetTaskResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_message: builtins.str
    @property
    def task(self) -> global___Task: ...
    def __init__(
        self,
        *,
        task: global___Task | None = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "task", b"task"]) -> None: ...

global___GetTaskResponse = GetTaskResponse

@typing.final
class GetChannelTasksRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    channel_id: builtins.int
    def __init__(
        self,
        *,
        channel_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_id", b"channel_id"]) -> None: ...

global___GetChannelTasksRequest = GetChannelTasksRequest

@typing.final
class GetChannelTasksResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASKS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_message: builtins.str
    @property
    def tasks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Task]: ...
    def __init__(
        self,
        *,
        tasks: collections.abc.Iterable[global___Task] | None = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "tasks", b"tasks"]) -> None: ...

global___GetChannelTasksResponse = GetChannelTasksResponse
